# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, verbose_name='лайк')),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'лайк',
                'verbose_name_plural': 'лайки',
            },
        ),
        migrations.CreateModel(
            name='LikeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Like', verbose_name='лайк')),
            ],
            options={
                'verbose_name': 'таблица лайков',
                'verbose_name_plural': 'таблицы лайков',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='вопрос')),
                ('full_question', models.CharField(max_length=8192, verbose_name='полный вопрос')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='дата создания вопроса')),
                ('rating', models.IntegerField(blank=True, default=0, verbose_name='рейтинг')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(upload_to='', verbose_name='название тега')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='TagTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='вопрос')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'таблица тегов',
                'verbose_name_plural': 'таблицы тегов',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='аватар')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='дата регистрации')),
                ('rating', models.IntegerField(blank=True, default=0, verbose_name='рейтинг')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.UserProfile', verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='liketable',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='вопрос'),
        ),
    ]
