# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=8192, verbose_name='ответ')),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.UserProfile', verbose_name='пользователь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name_plural': 'вопросы',
                'verbose_name': 'вопрос',
            },
        ),
    ]
