# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20170422_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='register_date',
            new_name='date',
        ),
    ]
