# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0008_auto_20170523_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, verbose_name='название тега'),
        ),
    ]
