# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_auto_20170523_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ask.Question', verbose_name='вопрос'),
        ),
    ]
