# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_auto_20170523_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='фамилия'),
        ),
    ]
